version: '2'
services:   
    potree:
      # restart: always
      image: cvast/cvast-potree:dev
      working_dir: /potree
      build: 
        context: .
        dockerfile: ./Dockerfile
      command: runserver
      environment:
      - AWS_ACCESS_KEY_ID=<your aws key ID>
      - AWS_SECRET_ACCESS_KEY=<your aws secret key>
      - SYNC_S3=False
      volumes:
      - ./pointcloud_input_folder:/pointcloud_input_folder
      ports:
        - '82:80'
