version: '2'
services:   
    potree:
      image: cvast/cvast-potree:1.0b
      working_dir: /potree
      build: 
        context: .
        dockerfile: ./Dockerfile
      command: runserver
      environment:
      - AWS_ACCESS_KEY_ID=<your aws key ID>
      - AWS_SECRET_ACCESS_KEY=<your aws secret key>
      - AWS_DEFAULT_REGION=us-east-1
      volumes:
      - potree-pointclouds:/var/www/potree/resources/pointclouds   
      - potree-pointclouds-input:/pointcloud_input_folder
      ports:
        - '80:80'


volumes:
    potree-pointclouds:
    potree-pointclouds-input:
